language: node_js
dist: trusty
sudo: required
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "vroegop-github"
before_script:
  - npm install -g polymer-cli
  - polymer install
  - polymer lint
script:
  - xvfb-run polymer test --skip-plugin sauce
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --skip-plugin local;
    fi
  - sonar-scanner
os: linux
group: stable
