---
language: node_js
dist: trusty
sudo: true
addons:
  sauce_connect: 
    username: "rjp.vroegop@gmail.com"
  jwt:
    secure: "BYeklID6yNeQmE/wxtJEottxjQRlvchC/s1Ck06XNAM1sFfobEtBwrl0edFFNZK0OJ5tHoqzEGyZxY3wH20pePQlZ+Eq17cXMjnE1HMuJD9JPN9bd55ljuW3W02gB+m24YayyiUrNhWV8FAm0E1djiFNwrZPbTuwGLmFokczFKOtTlQCjIF8A/qm/UfqRwz8a253/84aIWGZOaziSQKAgoLK0unNNyBOV19TvYP/qqRGED4gYQ1RJ7R1tcV4HQ88zXsqndTCT9d6ubUTIVOC1TAbb69Kdn4ecyI6eB9PSWhvRszAMSjNssyOfo702eJ4koRe0dQweJmBTWMUIz/AYm75VZIoohojZLVUvsofdFE8JC4szci1WMq5n7hfePT7HFilFf/Aw/2POvVxkdibARzgHEZWHd87Y+W/H4lzMckx5b9MTBdVcviLdXB7HhwiVwxN2tYiR7inXueD1UyKEa514mBW4mvLg6BWrwwc6lFqUMut78ctyVcSgB+nrVSofNfMX7XFS3Lw4BuR7zCUm0Dy7FpdHtQy4Iby8b0pKWmecuTNYcSu/CwS9/Kf4769dNkWg8XuU+HFXjJ8ze659Dv6zcbvDheyQKGRCKh2CF+AUusyvHo2ezbPt5OHmKbdtJLxlXe0ClPeP6inO2szaVgkCxJzLgCxrR/awxLCjeU="
  sonarcloud:
    organization: "vroegop-github"
    token:
      secure: "npjwnQDgwMA9ocZiIEeZNTq1NrIEUIyfptfzbr3rDqfiJNbQjt/MLbuj5I6yrSNgU5P5PhRTWehrwIT5/bjFhvZphMfawFSbU/J3MXzc53owRJBLF0XrQgo3y2JXBKxNcShB41D4kbv206RmeUlz0ZNhGSoSDXZKwFXy+Vl+NOB8H5QlmlObWAYjBuYWCEExqalc7UUR2m8vSDtYr0JP0iiJkXzTq0xzVwJvr4zzPsRweeR5PYZr22ERnPvIXSmcZsi8zpHCSUYlz2mLRHSbs+4fyF7nTH9DzcMMiOYIOMreworlf8IhECmJOwj4wm2cTPIDHX/zT95xgFzMBR7pwFV/62LF9C626MADmLePKXrUPgUxDgsIRsmcNLTDQeuiHfjV+5w25AbO72qb7cnLwFIueX/tZfqRnKY6dzLFnSByUkJaCBew6DucxIbve8xXpTPvmyL2D6BEiZsWf14iy06XJP7Pb27O2WK8spH9HSzj4Xq08sG414gt/1+wYQevMZx0UMBurxNQf5Vaxhp8ebWmOO+KGjOlzO31QcxGyNcQwBDOo1q7/6BEAa43n1bI5eYg77mAqosPDNnAPzOE9F8EncBAgjUY6Kn3yo4C6Ry09pDnKaQu2bKZGJTXeyvcyLJhAlbLUafDcKiE+HQIhQdqKSLGuoKBf5z9Kfb4t/I="
node_js: node
cache:
  directories:
  - node_modules
install:
- npm install -g polymer-cli
- npm install
- polymer install
before_script:
- polymer lint
script:
- xvfb-run polymer test
- sonar-scanner
os: linux
group: stable
