language: node_js
dist: trusty
sudo: required
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "vroegop-github"
before_script:
  - npm install -g polymer-cli
  - npm install -g wct-istanbub
  - polymer install
  - polymer lint
  - >-
   npm run update-types && git diff --exit-code || (echo -e
   '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
   update-types".' && false)
script:
  - xvfb-run polymer test
  - true || if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce; fi
  - sonar-scanner
os: linux
group: stable
