---
language: node_js
dist: trusty
sudo: true
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
  sonarcloud:
    organization: "vroegop-github"
node_js: node
cache:
  directories:
  - node_modules
install:
- npm install -g polymer-cli
- npm install
- polymer install
before_script:
- polymer lint
script:
- xvfb-run polymer test --plugin sauce
- sonar-scanner
os: linux
group: stable
