/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   color-selector.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />

/**
 * `color-selector`
 * Paper color picker including fonts
 */
declare class ColorSelector extends Polymer.Element {
  name: object|null|undefined;
  normalColor: string|null|undefined;
  lightColor: string|null|undefined;
  darkColor: string|null|undefined;
  normalFontColor: string|null|undefined;
  darkFontColor: string|null|undefined;
  lightFontColor: string|null|undefined;
  normalHeadFontColor: string|null|undefined;
  darkHeadFontColor: string|null|undefined;
  lightHeadFontColor: string|null|undefined;
  target: string|null|undefined;
  changeColor(): any;
  _isPrimary(): any;
}

interface HTMLElementTagNameMap {
  "color-selector": ColorSelector;
}
