/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   material-paper-color-picker.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="color-selector.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../iron-icons/iron-icons.d.ts" />

/**
 * `material-paper-color-picker`
 * Paper color picker including fonts
 */
declare class MaterialPaperColorPicker extends Polymer.Element {
  primaryTitle: string|null|undefined;
  secondaryTitle: string|null|undefined;
  align: string|null|undefined;
  cpOpen: string|null|undefined;
  primaryColors: any[]|null|undefined;
  secondaryColors: any[]|null|undefined;
  emptyPrimary: boolean|null|undefined;
  emptySecondary: boolean|null|undefined;
  hidePrimary: boolean|null|undefined;
  hideSecondary: boolean|null|undefined;
  icon: string|null|undefined;
  connectedCallback(): any;
  toggleColorPicker(event: any): any;
  initPickerButton(): any;
  setAlignStyle(): any;
  _bothColors(): any;
}

interface HTMLElementTagNameMap {
  "material-paper-color-picker": MaterialPaperColorPicker;
}
