/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   remember-color.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />

/**
 * Remember-color
 *
 * This custom element listens to the document level event 'color-picked', which is fired by the color-selector element.
 * This element will save the picked values in the localstorage. On page-refresh, this element sets the CSS variables based
 * on the local-storage value.
 *
 * `remember-color`
 * Remembers the color you picked with the color-selector
 */
declare class RememberColor extends Polymer.Element {
  connectedCallback(): any;
  getOldColor(): any;
  colorPicked(e: any): any;
  setColors(color: any): any;
}

interface HTMLElementTagNameMap {
  "remember-color": RememberColor;
}
