/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   remember-color.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />

/**
 * Remember color
 *
 * `remember-color`
 * Remembers the color you picked with the color-selector
 */
declare class RememberColor extends Polymer.Element {
  connectedCallback(): any;
  getOldColor(): any;
  colorPicked(e: any): any;
  setColors(color: any): any;
}

interface HTMLElementTagNameMap {
  "remember-color": RememberColor;
}
